### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by barca-cloud** [TheYoBots/github-hack#1]
how to?

**Comment by TheYoBots** [comment]
Quoting the README.md file,

> All I'm going to say is that this repository is a GitHub hack. This doesn't involving in stealing accounts and getting ip addresses and other messed malicious stuff. This is just some fun hack, which I'm sure anyone (almost anyone) would love to have. How to run this repository to make the hack work or how to use it and what it does is something I will not mention.
>
> It's all up to you to figure it out if you really want to know what it does 👀 👀 👀

**Comment by SriMethan** [comment]
`node index.js`
